[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "zoglin_pygments_plugin" # change this to a package name for your plugin
version = "0.0.1"
dependencies = ["pygments"]
readme = "README.md"

# Declare plugin lexers in this table. The key (like `example_lexer` below) are
# not significant. The value has the form `module_name:ClassName`. The lexer
# class will be imported using `from module_name import ClassName`.

# See the attributes declared in example_lexer.py for how to configure the
# language names and file patterns.

[project.entry-points."pygments.lexers"]
zoglin_lexer = "zoglin_pygments_plugin:ZoglinLexer"

# This is a test command. Running it should print:
#
# [ff0000]foo
# [black]<tab><tab>bar # tabs here
#
# - Our custom lexer highlights "foo" as keyword,
# - Our custom style uses red (ff0000) for keywords,
# - Our custom formatter prints colors in brackets,
# - Our custom filter replaces tabs with "<tab>".
#
# Run with
#
#   hatch run test

[tool.hatch.envs.default.scripts]
test = "pygmentize -l zoglin test.exmpl"
